---
- hosts: all
  sudo: yes
  vars:
    cluster_name: Test Cluster
    vagrant_ip: 192.168.10.11
    seeds: 192.168.10.11
    spark_version: spark-1.6.1-bin-hadoop2.4
    connector_jar: spark-cassandra-connector-1.6.0-M2-s_2.10.jar

  tasks:
  - name: install htop
    apt: name=htop state=present

  roles:
    - java
    - cassandra
    - opscenter
    - spark

  tasks:
    - name: start a spark master
      command: nohup /opt/{{ spark_version }}/sbin/start-master.sh
      tags:
        - spark

    - name: start a spark worker
      command: nohup /opt/{{ spark_version }}/bin/spark-class org.apache.spark.deploy.worker.Worker  spark://{{ vagrant_ip }}:7077
      async: 315360000
      poll: 0
      tags:
        - spark
