# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.box = "ubuntu/trusty64"
  config.vm.box = "larryli/vivid64"

  config.vm.host_name = "cassandra-spark"
  config.vm.network :private_network, ip: "192.168.10.11"
  config.vm.network :forwarded_port, guest: 22, host: 1233
  config.ssh.forward_agent = true # Enables agent forwarding over SSH connections.
  config.ssh.forward_x11 = true # Enables X11 forwarding over SSH connections.

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.cpus = 2
    end

end
